language: scala
scala:
  - 2.12.5
services:
  - docker
before_install:
  - nvm install 9
script:
  - sbt -jvm-opts travis/jvmopts.compile client/fastOptJS
  - sbt -jvm-opts travis/jvmopts.compile server/docker:publishLocal
deploy:
  provider: script
  script: bash deploy.sh
  skip_cleanup: true
  on:
    branch: master
notifications:
  slack: v2land:xoeT2IXt8yCaUfMxoBbXrSZD
