language: scala
scala:
  - 2.12.5
services:
  - docker
before_install:
  - nvm install 9
script:
  - bash ./build-frontend.sh
  - sbt -jvm-opts travis/jvmopts.compile docker:publishLocal
deploy:
  provider: script
  script: bash deploy.sh
  on:
    branch: master
notifications:
  slack: v2land:xoeT2IXt8yCaUfMxoBbXrSZD
