language: scala
scala:
  - 2.12.5
services:
  - docker
before_install:
  - nvm install 9
script:
  - sbt -jvm-opts travis/jvmopts.compile client/fullOptJS
  - sbt -jvm-opts travis/jvmopts.compile prodServer/test
  - sbt -jvm-opts travis/jvmopts.compile prodServer/docker:publishLocal
deploy:
  provider: script
  script: bash deploy.sh
  skip_cleanup: true
  on:
    branch: master
notifications:
  slack: v2land:xoeT2IXt8yCaUfMxoBbXrSZD
sudo: false
cache:
  directories:
    - $HOME/.ivy2/cache
    - $HOME/.sbt
before_cache:
    - find $HOME/.ivy2/cache -name "ivydata-*.properties" -print -delete
    - find $HOME/.sbt        -name "*.lock"               -print -delete

